-- inserts idiomas.valor_nivel_idioma
INSERT INTO idiomas.valor_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (1,'Regular','Valor regular','Regular', true,1, now(), now());
INSERT INTO idiomas.valor_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (2,'Bien','Valor bien','Bien', true,2, now(), now());
INSERT INTO idiomas.valor_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (3,'Muy bien','Valor muy bien','Muy bien', true,3, now(), now());

-- inserts idiomas.clasificacion_nivel_idioma
INSERT INTO idiomas.clasificacion_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (1,'A1','Nivel A1','A1', true,1, now(), now());
INSERT INTO idiomas.clasificacion_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (2,'A2','Nivel A2','A2', true,2, now(), now());
INSERT INTO idiomas.clasificacion_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (3,'B1','Nivel B1','B1', true,3, now(), now());
INSERT INTO idiomas.clasificacion_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (4,'B2','Nivel B2','B2', true,4, now(), now());
INSERT INTO idiomas.clasificacion_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (5,'C1','Nivel C1','C1', true,5, now(), now());
INSERT INTO idiomas.clasificacion_nivel_idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (6,'C2','Nivel C2','C2', true,6, now(), now());

-- inserts idiomas.idioma
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (1,'Español, castellano','idioma Español, castellano','es', true,1, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (2,'Inglés','idioma Inglés','en', true,2, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (3,'Abkhaz','idioma Abkhaz','ab', true,3, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (4,'Afar','idioma Afar','aa', true,4, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (5,'Africanos','idioma Africanos','af', true,5, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (6,'Akan','idioma Akan','ak', true,6, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (7,'Albania','idioma Albania','sq', true,7, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (8,'Amárico','idioma Amárico','am', true,8, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (9,'Árabe','idioma Árabe','ar', true,9, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (10,'Aragonés','idioma Aragonés','an', true,10, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (11,'Armenio','idioma Armenio','hy', true,11, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (12,'Assamese','idioma Assamese','as', true,12, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (13,'Avaric','idioma Avaric','av', true,13, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (14,'Avestan','idioma Avestan','ae', true,14, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (15,'Aymara','idioma Aymara','ay', true,15, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (16,'Azerbaiyán','idioma Azerbaiyán','az', true,16, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (17,'Bambara','idioma Bambara','bm', true,17, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (18,'Bashkir','idioma Bashkir','ba', true,18, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (19,'Vasco','idioma Vasco','eu', true,19, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (20,'Belarús','idioma Belarús','be', true,20, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (21,'Bengalí','idioma Bengalí','bn', true,21, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (22,'Bihari','idioma Bihari','bh', true,22, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (23,'Bislama','idioma Bislama','bi', true,23, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (24,'Bosnia','idioma Bosnia','bs', true,24, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (25,'Breton','idioma Breton','br', true,25, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (26,'Búlgaro','idioma Búlgaro','bg', true,26, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (27,'Burmese','idioma Burmese','my', true,27, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (28,'Catalán','idioma Catalán','ca', true,28, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (29,'Chamorro','idioma Chamorro','ch', true,29, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (30,'Chechenio','idioma Chechenio','ce', true,30, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (31,'Chichewa, Chewa, Nyanja','idioma Chichewa, Chewa, Nyanja','ny', true,31, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (32,'Chino','idioma Chino','zh', true,32, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (33,'Chuvashia','idioma Chuvashia','cv', true,33, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (34,'Cornualles','idioma Cornualles','kw', true,34, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (35,'Corso','idioma Corso','co', true,35, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (36,'Cree','idioma Cree','cr', true,36, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (37,'Croacia','idioma Croacia','hr', true,37, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (38,'Checo','idioma Checo','cs', true,38, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (39,'Danés','idioma Danés','da', true,39, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (40,'Divehi, Dhivehi, Maldivas','idioma Divehi, Dhivehi, Maldivas','dv', true,40, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (41,'Holandés','idioma Holandés','nl', true,41, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (42,'Dzongkha','idioma Dzongkha','dz', true,42, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (43,'Esperanto','idioma Esperanto','eo', true,43, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (44,'Estonia','idioma Estonia','et', true,44, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (45,'Ewe','idioma Ewe','ee', true,45, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (46,'Faroese','idioma Faroese','fo', true,46, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (47,'Fiji','idioma Fiji','fj', true,47, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (48,'Finlandés','idioma Finlandés','fi', true,48, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (49,'Francés','idioma Francés','fr', true,49, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (50,'Fula, Fulah, Pulaar, Pular','idioma Fula, Fulah, Pulaar, Pular','ff', true,50, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (51,'Galicia','idioma Galicia','gl', true,51, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (52,'Georgiano','idioma Georgiano','ka', true,52, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (53,'Alemán','idioma Alemán','de', true,53, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (54,'Griego Moderno','idioma Griego Moderno','el', true,54, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (55,'Guaraní','idioma Guaraní','gn', true,55, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (56,'Gujarati','idioma Gujarati','gu', true,56, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (57,'Haitiano, creole haitiano','idioma Haitiano, creole haitiano','ht', true,57, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (58,'Hausa','idioma Hausa','ha', true,58, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (59,'Hebreo (moderno)','idioma Hebreo (moderno)','he', true,59, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (60,'Herero','idioma Herero','hz', true,60, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (61,'Hindi','idioma Hindi','hi', true,61, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (62,'Hiri Motu','idioma Hiri Motu','ho', true,62, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (63,'Húngaro','idioma Húngaro','hu', true,63, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (64,'Interlingua','idioma Interlingua','ia', true,64, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (65,'Indonesio','idioma Indonesio','id', true,65, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (66,'Interlingue','idioma Interlingue','ie', true,66, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (67,'Irlanda','idioma Irlanda','ga', true,67, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (68,'Igbo','idioma Igbo','ig', true,68, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (69,'Inupiaq','idioma Inupiaq','ik', true,69, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (70,'Ido','idioma Ido','io', true,70, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (71,'Islandés','idioma Islandés','is', true,71, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (72,'Italiano','idioma Italiano','it', true,72, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (73,'Inuktitut','idioma Inuktitut','iu', true,73, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (74,'Japonés','idioma Japonés','ja', true,74, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (75,'Javanés','idioma Javanés','jv', true,75, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (76,'Kalaallisut, Groenlandia','idioma Kalaallisut, Groenlandia','kl', true,76, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (77,'Canarés','idioma Canarés','kn', true,77, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (78,'Kanuri','idioma Kanuri','kr', true,78, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (79,'Cachemira','idioma Cachemira','ks', true,79, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (80,'Kazajstán','idioma Kazajstán','kk', true,80, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (81,'Khmer','idioma Khmer','km', true,81, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (82,'Kikuyu, Gikuyu','idioma Kikuyu, Gikuyu','ki', true,82, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (83,'Kinyarwanda','idioma Kinyarwanda','rw', true,83, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (84,'Kirguises, Kirguistán','idioma Kirguises, Kirguistán','ky', true,84, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (85,'Komi','idioma Komi','kv', true,85, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (86,'Kongo','idioma Kongo','kg', true,86, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (87,'Corea','idioma Corea','ko', true,87, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (88,'Kurdo','idioma Kurdo','ku', true,88, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (89,'Kwanyama, Kuanyama','idioma Kwanyama, Kuanyama','kj', true,89, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (90,'Latin','idioma Latin','la', true,90, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (91,'Luxemburgués, Luxemburgués','idioma Luxemburgués, Luxemburgués','lb', true,91, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (92,'Luganda','idioma Luganda','lg', true,92, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (93,'Limburgués, Limburgan, Limburger','idioma Limburgués, Limburgan, Limburger','li', true,93, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (94,'Lingala','idioma Lingala','ln', true,94, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (95,'Lao','idioma Lao','lo', true,95, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (96,'Lituano','idioma Lituano','lt', true,96, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (97,'Luba-Katanga','idioma Luba-Katanga','lu', true,97, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (98,'Letonia','idioma Letonia','lv', true,98, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (99,'Manx','idioma Manx','gv', true,99, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (100,'Macedonia','idioma Macedonia','mk', true,100, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (101,'Madagascar','idioma Madagascar','mg', true,101, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (102,'Malayo','idioma Malayo','ms', true,102, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (103,'Malayalam','idioma Malayalam','ml', true,103, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (104,'Maltés','idioma Maltés','mt', true,104, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (105,'Māori','idioma Māori','mi', true,105, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (106,'Maratí (Marathi)','idioma Maratí (Marathi)','mr', true,106, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (107,'De las Islas Marshall','idioma De las Islas Marshall','mh', true,107, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (108,'Mongolia','idioma Mongolia','mn', true,108, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (109,'Nauru','idioma Nauru','na', true,109, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (110,'Navajo, Navaho','idioma Navajo, Navaho','nv', true,110, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (111,'Noruego Bokmål','idioma Noruego Bokmål','nb', true,111, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (112,'Ndebele del Norte','idioma Ndebele del Norte','nd', true,112, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (113,'Nepali','idioma Nepali','ne', true,113, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (114,'Ndonga','idioma Ndonga','ng', true,114, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (115,'Noruego Nynorsk','idioma Noruego Nynorsk','nn', true,115, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (116,'Noruego','idioma Noruego','no', true,116, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (117,'Nuosu','idioma Nuosu','ii', true,117, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (118,'Ndebele del sur','idioma Ndebele del sur','nr', true,118, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (119,'Occitano','idioma Occitano','oc', true,119, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (120,'Ojibwe, Ojibwa','idioma Ojibwe, Ojibwa','oj', true,120, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (121,'Antiguo eslavo eclesiástico, Iglesia eslava, eslavo eclesiástico, antiguo Búlgaro, Esclavo viejo','idioma Antiguo eslavo eclesiástico, Iglesia eslava, eslavo eclesiástico, antiguo Búlgaro, Esclavo viejo','cu', true,121, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (122,'Oromo','idioma Oromo','om', true,122, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (123,'Oriya','idioma Oriya','or', true,123, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (124,'Osetia del Sur, osetio','idioma Osetia del Sur, osetio','os', true,124, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (125,'Panjabi, Punjabi','idioma Panjabi, Punjabi','pa', true,125, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (126,'Pāli','idioma Pāli','pi', true,126, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (127,'Persa','idioma Persa','fa', true,127, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (128,'Polaco','idioma Polaco','pl', true,128, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (129,'Pashto, Pushto','idioma Pashto, Pushto','ps', true,129, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (130,'Portugués','idioma Portugués','pt', true,130, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (131,'Quechua','idioma Quechua','qu', true,131, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (132,'Romanche','idioma Romanche','rm', true,132, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (133,'Kirundi','idioma Kirundi','rn', true,133, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (134,'Rumania, Moldavia, Moldavan','idioma Rumania, Moldavia, Moldavan','ro', true,134, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (135,'Ruso','idioma Ruso','ru', true,135, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (136,'Sánscrito (samskrta)','idioma Sánscrito (samskrta)','sa', true,136, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (137,'Sardo','idioma Sardo','sc', true,137, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (138,'Sindhi','idioma Sindhi','sd', true,138, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (139,'Sami del norte','idioma Sami del norte','se', true,139, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (140,'Samoa','idioma Samoa','sm', true,140, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (141,'Sango','idioma Sango','sg', true,141, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (142,'Serbio','idioma Serbio','sr', true,142, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (143,'Gaélico escocés, gaélico','idioma Gaélico escocés, gaélico','gd', true,143, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (144,'Shona','idioma Shona','sn', true,144, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (145,'Cingalés, singalés','idioma Cingalés, singalés','si', true,145, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (146,'Eslovaca','idioma Eslovaca','sk', true,146, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (147,'Esloveno','idioma Esloveno','sl', true,147, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (148,'Somalí','idioma Somalí','so', true,148, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (149,'Southern Sotho','idioma Southern Sotho','st', true,149, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (150,'Sundanese','idioma Sundanese','su', true,150, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (151,'Swahili','idioma Swahili','sw', true,151, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (152,'Swati','idioma Swati','ss', true,152, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (153,'Sueco','idioma Sueco','sv', true,153, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (154,'Tamil','idioma Tamil','ta', true,154, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (155,'Telugu','idioma Telugu','te', true,155, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (156,'Tayikistán','idioma Tayikistán','tg', true,156, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (157,'Tailandia','idioma Tailandia','th', true,157, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (158,'Tigrinya','idioma Tigrinya','ti', true,158, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (159,'Tibetano estándar, Tibetano, Central','idioma Tibetano estándar, Tibetano, Central','bo', true,159, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (160,'Turkmenistán','idioma Turkmenistán','tk', true,160, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (161,'Tagalo','idioma Tagalo','tl', true,161, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (162,'Tswana','idioma Tswana','tn', true,162, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (163,'Tonga (Islas Tonga)','idioma Tonga (Islas Tonga)','to', true,163, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (164,'Turco','idioma Turco','tr', true,164, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (165,'Tsonga','idioma Tsonga','ts', true,165, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (166,'Tártara','idioma Tártara','tt', true,166, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (167,'Twi','idioma Twi','tw', true,167, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (168,'Tahitian','idioma Tahitian','ty', true,168, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (169,'Uighur, Uyghur','idioma Uighur, Uyghur','ug', true,169, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (170,'Ucrania','idioma Ucrania','uk', true,170, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (171,'Urdu','idioma Urdu','ur', true,171, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (172,'Uzbeko','idioma Uzbeko','uz', true,172, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (173,'Venda','idioma Venda','ve', true,173, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (174,'Vietnamita','idioma Vietnamita','vi', true,174, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (175,'Volapük','idioma Volapük','vo', true,175, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (176,'Valonia','idioma Valonia','wa', true,176, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (177,'Galés','idioma Galés','cy', true,177, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (178,'Wolof','idioma Wolof','wo', true,178, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (179,'Oeste de Frisia','idioma Oeste de Frisia','fy', true,179, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (180,'Xhosa','idioma Xhosa','xh', true,180, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (181,'Yiddish','idioma Yiddish','yi', true,181, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (182,'Yoruba','idioma Yoruba','yo', true,182, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (183,'Zhuang, Chuang','idioma Zhuang, Chuang','za', true,183, now(), now());
INSERT INTO idiomas.idioma(id,nombre, descripcion, codigo_abreviacion, activo, numero_orden, fecha_creacion, fecha_modificacion) VALUES (184,'Zulu','idioma Zulu','zu', true,184, now(), now());